### ISSUE TITLE
FormattedPlural support

### ISSUE THREAD

**Issue by bardt** [yahoo/babel-plugin-react-intl#11]
Not sure if this is my misunderstanding or design issue. Right now this plugin doesn't seem to work with `FormattedPlural` tag from react-intl. Are there any plans to support it or will it be dropped in next versions of react-intl?

**Comment by bardt** [comment]
Sorry, solved with this comment https://github.com/yahoo/react-intl/issues/162#issuecomment-149274627

**Comment by ericf** [comment]
@bardt does this distinction between `<FormattedPlural>` and `<FormattedMessage>` make sense to you? The addition of `<FormattedPlural>` was to expand the audience to single-language apps that React Intl is useful for.

An interesting aspect of you brining this up is that if you're using this Babel plugin, then you **shouldn't** be using `<FormattedPlural>` because it means you likely have hard-coded strings in your app that won't be extracted for translation. So the plugin could be updated to warn when it encounters a `<FormattedPlural>` declaration… what do you think?

**Comment by bardt** [comment]
@ericf right now I see an inconvenience, probably caused by changes in react-intl v2, between official docs, v2 tread instructions and this plugin. It took some hours of experimenting to finally get it working like I supposed it to. I'd definitely vote for better developer experience we are used to in React itself (meaningful warnings, suggestion of using react devtools extension etc.). 

Right now I'm close to a big deadline on a project I'm trying to use react-intl on, so have no spare time. After that, I could help with some changes to this plugin, according to my own dev experience.

**Comment by ericf** [comment]
@bardt no worries, I'm happy to add in this warning. Feel free to ping me if you run into any other issues as you work towards your deadline!
