### ISSUE TITLE
Move 'printICUMessage(ast)' into separate project

### ISSUE THREAD

**Issue by rightaway** [yahoo/babel-plugin-react-intl#19]
The `printICUMessage(ast)` function which was suggested to me in https://github.com/yahoo/intl-messageformat/issues/118 works great and is very useful as a standalone tool to convert an ICU AST into an ICU string pattern. Would you consider moving this into its own separate project so that I could depend on it directly in my package.json? Would be better so that I don't have to copy-paste the code and keep it in sync as updates are made upstream. Could be called for example something like `icuAstToPattern`.

**Comment by rightaway** [comment]
Would you accept a pull request for this? I'm happy to take it on.

**Comment by ericf** [comment]
Moving it to a separate repo seems like overkill to me.

What I'd like to do is move this code into the react-intl repo and setup that Git repo to support multiple npm packages. That way all the related code is in one place and CI is setup once. You're free to take this code and do what you wish in accordance to the license.

I'm going to close this issue, since I don't want to manage _more_ Git repos.
