### ISSUE TITLE
Error when using a reference to an object in `defineMessages`

### ISSUE THREAD

**Issue by jasonmorita** [yahoo/babel-plugin-react-intl#78]
When I try to use a reference to an object, either via `const` or `import`, I get an error when trying to run `babel-plugin-react-intl`.

`Module build failed: SyntaxError: [React Intl] `defineMessages()` must be called with an object expression with values that are React Intl Message Descriptors, also defined as object expressions.`

My goal is to import the string from an external file to make editing more friendly to non-devs.

Note: the plugins was only in the `.babelrc`

Here is a branch with what I am trying to get working: 
https://github.com/jasonmorita/react-intl-translate/tree/defineMessages

**Comment by ericf** [comment]
Since Babel is a compiler and not a JavaScript interpreter or runtime you'll need to define the messages you want extracted at the `defineMessages()` call site. This means that `defineMessages()` should only be used where the message is actually defined, and you shouldn't use it where the message is referenced.

**Comment by jasonmorita** [comment]
HI @ericf, this issue was also present when I declared the message object as a `const` right above the call site (not with `import` although that is preferable). Is this also expected? This seems like a pretty common use-case, do you know of a way others have solved this issue? I know for some projects, having the content/messages in the components may not be efficient.

**Comment by ericf** [comment]
The whole point of this plugin is to extract the messages from source code and `defineMessages()` is a hook for this and its expected that the message descriptor exists within the call site. `defineMessages()` is an identify function and returns the object passed in, so the most common use case is:

```js
const messages = defineMessages({
  greeting: {
    id: 'home.greeting',
    defaultMessage: 'Hello, {name}!'
  }
});
```

**Comment by jasonmorita** [comment]
@ericf Thanks, looks like I was trying to use this for something it was not intended for.

**Comment by ericf** [comment]
I don't fully understand what your use case is. Can you explain it a bit more and I might be able to help.

**Comment by jasonmorita** [comment]
@ericf What I was looking to do was to store our strings in JSON and import the properties needed directly into each component. This would allow non-devs to edit the strings without needing to get into the component code directly. But, from what you have explained, it seems like the point of the plugin is to do just the opposite, which is to allow you to have your strings in the code, then "export" them later for translation. The use-cases seem at odds and I now see the `defineMessages` is really just used for scraping. Makes sense. Thank you!

**Comment by pretentiousgit** [comment]
Plus one for this being a bug, since it prevents the use of generated `id` strings and namespacing of those strings in reusable components (such as address or form components).

**Comment by ericf** [comment]
@pretentiousgit I don't know what exactly you're plus-one-ing. Can you open a new issue with more details?

**Comment by pretentiousgit** [comment]
@ericf I'm +1-ing being able to pass defineMessages() a reference to an object, like so:

I've spent some time in the plugin this morning, and I see that defineMessages is truly v. bare but also that `babel-plugin-react-intl` scrapes for things that are defined _before_ compilation, so I can't do this, clearly - but this is pretty important to be able to build re-usable form components that take a namespace on translateable strings, ie: how we avoid typos in many-character-long ID strings.

I'm looking at the problem, but AST is very, very new to me, so I'm having a lot of trouble (as one approach) extracting the namespace from `path.callee` and interpolating it on compilation, for example... but avoiding the interpolation/interpretation/something in `babel-plugin-react-intl` would mean transforming `defineMessages` to handle references somehow. It's challenging because the plugin catches `definedMessages` before I can transform them in `react-intl` itself.

Sample of thing that should work, JS-style:
```js
export default (formatMessage, namespace) => {
  console.log(namespace);
  const startMessage = {
              address: {
                id: `${namespace}.address`,
                defaultMessage: 'Street Address'
              },
              addressMeta: {
                id: `${namespace}.addressMeta`,
                defaultMessage: 'Address can’t be a P.O. box.'
              },
              suite: {
                id: `${namespace}.suite`,
                defaultMessage: 'Suite (Optional)'
              },
              city: {
                id: `${namespace}.city`,
                defaultMessage: 'City'
              },
              province: {
                id: `${namespace}.province`,
                defaultMessage: 'Province'
              },
              postalcode: {
                id: `${namespace}.postalcode`,
                defaultMessage: 'Postal Code'
              }
    };

  const messages = defineMessages(startMessage);

etc.etc.etc. function continues making use of formatMessage(messages.suite)
})
```

**Comment by ericf** [comment]
@pretentiousgit the point of this plugin is to be able to extract data that's statically defined in JS code at build time. Therefore if messages aren't able to be extracted statically, this isn't going to help much. If you're form components are truly reusable, then you should be able to define `<CityInput>` with a static `id` `"input.city"` or something, and reuse it that way.

If you truly need to apply a namespace, then do so after the messages have been extracted by processing the `.json` file that this plugin creates, and make sure that namespace is also provided at runtime so you can pass it to things like `<FormattedMessage id={`${namespace}.city`}>`.

**Comment by gurbraj** [comment]
@pretentiousgit, I agree with you that there should exist functionality for doing that!

The way I've worked around it is to write a script that runs on node before build-time, that takes `messagesToBeDefined`and maps it into `definedMessages`, and puts `definedMessages` into a file in the /src -folder, so that they are there for build-time. Then in my components, I just import from that that fie

**Comment by jasonmorita** [comment]
Blast from the past!
