### ISSUE TITLE
[feature-request] File(s) for unused translations

### ISSUE THREAD

**Issue by maniax89** [yahoo/babel-plugin-react-intl#86]
This component is great for visiting all the files that are currently using the react-intl, but is there a way to determine if those files are actually using the messages defined?  I have found that sometimes messages get picked up that are not actually used anywhere in the code and it would be nice if a static analysis could check that.

How hard would this be to accomplish? Are there other tools out there that can accomplish this already?

**Comment by ericf** [comment]
If the messages are defined via `<FormattedMessage>`, then you'd know they are used. But anything defined via `defineMessages()` would be much harder to track and basically involve creating a JS interpreter similar to Flow to check that the messages are used. It's also possible for people to define all their messages in a single module and import them from the component modules — checking this case won't work well within Babel since it operates on a per-file basis.

**Comment by maniax89** [comment]
Ah yes, we currently use the `defineMessages` approach and I guess that's how we got into this situation. 

Do you have any other recommendations? Or am I the first one to have this problem?

**Comment by ericf** [comment]
There's several changes in the works for React Intl that should make it simpler for defining messages inline:

- https://github.com/yahoo/react-intl/pull/612, https://github.com/yahoo/babel-plugin-react-intl/pull/70
- https://github.com/yahoo/react-intl/issues/513#issuecomment-252114827

It might be that these changes alleviate the need for you to use `defineMessages()`.

**Comment by maniax89** [comment]
Ah I see ok. Yeah I can see how it would not be easy to implement in a static way so I guess I can close this issue.
